//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Do_AN
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAIKHOAN
    {
        public string TK { get; set; }
        public string MK { get; set; }
        public string MACV { get; set; }
        public string CV { get; set; }
        public string MANV { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
